language: node_js
node_js:
  - '0.12'
before_install:
  - 'gem update --system'
  - 'npm update'
before_script:
  - 'npm install -g grunt-cli bower'
  - 'bower update --force'
script:
    - 'grunt --gruntfile .gruntc.js --stack'
notifications:
  email: false
